# This is the configuration used to check the rubocop source code.

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'config/initializers/devise.rb'
  TargetRubyVersion: 2.0

Documentation:
    Enabled: false

Style/IfUnlessModifier:
  MaxLineLength: 90

Style/Encoding:
  EnforcedStyle: never
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/IndentHeredoc:
  EnforcedStyle: powerpack

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb'

Lint/UselessAccessModifier:
  MethodCreatingMethods:
    - 'def_matcher'
    - 'def_node_matcher'

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'db/*.rb'

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*.rb'

    # Offense count: 84
Metrics/AbcSize:
  Max: 19

# Offense count: 36
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 171

# Offense count: 26
Metrics/CyclomaticComplexity:
  Max: 7

# Offense count: 136
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 20

# Offense count: 12
# Configuration parameters: CountComments.
Metrics/ModuleLength:
  Max: 156

Metrics/LineLength:
  Max: 120
